---
title: "DNA Methylation Signature of a Lifestyle-based Resilience Index for Cognitive Health"
subtitle: "LONDON brain blood correlation"
author: 
  - Wei Zhang^[University of Miami]
  - Lily Wang^[University of Miami]
date: "`r Sys.Date()`"
output:
  rmarkdown::html_document:
    highlight: pygments
    theme: yeti
    toc: true
    number_sections: true
    df_print: paged
    code_download: false
    toc_float:
      collapsed: yes
    toc_depth: 3
editor_options:
  chunk_output_type: inline    
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
dir.base <- "../.."
dir.results <- file.path(dir.base, "analysis_results")
dir.results.res <- file.path(dir.results, "resilience")
dir.results.combp <- file.path(dir.results, "combp")
dir.results.corr <- file.path(dir.results, "brain_blood_corr")
dir.data <- file.path(dir.base,"../DATASETS/") 
dir.london <- file.path(dir.data, "LONDON/")
dir.london.data <- file.path(dir.london, "DNAm/pca_filtering")
dir.london.pheno <- file.path(dir.london, "Phenotype/processed")
dir.data.corr <- file.path(dir.base, "data/brain_blood_corr/")
dir.data.aux <- file.path(dir.data,"Aux_Sync") 
for(p in grep("dir",ls(),value = T)) dir.create(get(p),recursive = TRUE,showWarnings = FALSE)
```

```{r message = F, warning=F}
source("../utility/cpg_test.R")
source("../utility/annotation.R")
source("../utility/plot.R")
```

# Load data

## London

```{r}
brain_beta <- readRDS(
  file.path(dir.london.data, "BRAIN/London_PFC_QNBMIQ_PCfiltered_withStageExclude_XY.RDS")
)
brain_pheno <- readRDS(
  file.path(dir.london.pheno, "pheno107_PFC_withNeuronProp_withStageExclude_df.RDS")
)
blood_beta <- readRDS(
  file.path(dir.london.data, "BLOOD/London_QNBMIQ_PCfiltered_withStatusExclude_XY.RDS")
)
blood_pheno <- readRDS(
  file.path(dir.london.pheno, "pheno_BLOOD_withBloodProp_withStatusExclude_df.rds")
)
```

## Limit samples in both datasets

```{r}
### Renames variables
colnames(brain_pheno)[c(1, 3:ncol(brain_pheno))] <- paste0(
  "brain_", colnames(brain_pheno)[c(1, 3:ncol(brain_pheno))]
)
colnames(blood_pheno)[c(1, 3:ncol(blood_pheno))] <- paste0(
  "blood_", colnames(blood_pheno)[c(1, 3:ncol(blood_pheno))]
)

### Merge datasets
pheno_final <- merge(
  brain_pheno, blood_pheno,
  by = "subject.id"
) #dim: 69 23

### Limit beta matrices to samples in pheno_final
brain_beta_final <- brain_beta[, pheno_final$brain_sample]
blood_beta_final <- blood_beta[, pheno_final$blood_sample]
```

## Resilience results

```{r message = F}
## Load meta results
results <- read_csv(
  file.path(dir.results.res,
            "Resilience_rlm_model_results_bacon.csv")
) %>% dplyr::select(
  cpg, seqnames, start, end, width, Relation_to_Island,
  UCSC_RefGene_Name, UCSC_RefGene_Group, GREAT_annotation, Estimate.bacon, pValue.bacon
)

## Sig single cpgs
cpgs.sig <- results %>% filter(pValue.bacon < 1e-05) %>%
  pull(cpg) ## 56

## Load comb-p DMR results
sig.dmr <- read_csv(
  file.path(dir.results.combp, "combp_resilience_rlm_filtered_results_annotated.csv")
) 
sig.dmr <- str_split(sig.dmr$cpgs_in_region, ",") %>% unlist() ## 134

write.csv(
  data.frame(unique(c(sig.dmr, cpgs.sig))),
  file.path(dir.data.corr, "Sig_CpGs_for_input_BEcon.csv"),
  row.names = F
)
```

# Calculate correlation

```{r}
### Limit blood_beta and brain_beta to probes in main_cpgs
brain_beta_cpgs <- brain_beta_final[
  row.names(brain_beta_final) %in% unique(c(sig.dmr, cpgs.sig)),
  ]

blood_beta_cpgs <- blood_beta_final[
  row.names(blood_beta_final) %in% unique(c(sig.dmr, cpgs.sig)),
  ]

identical(dim(brain_beta_cpgs), dim(blood_beta_cpgs))
```

## Residual

```{r message = F}
pheno_final$brain_slide <- as.character(pheno_final$brain_slide)
# brain residuals
brain_resid <- methyl_adj(
  mat = brain_beta_cpgs,
  pheno = pheno_final,
  adjust_var = c("brain_age.brain", "brain_sex", "brain_prop.neuron", "brain_slide"),
  convert_to_M = T,
  return_to_beta = F
)
# blood residuals
pheno_final$blood_Gran <- pheno_final$blood_Eosino + pheno_final$blood_Neutro
blood_resid <- methyl_adj(
  mat = blood_beta_cpgs,
  pheno = pheno_final,
  adjust_var = c("blood_age.blood", "blood_sex", "blood_slide", 
                 "blood_B", "blood_CD4T", "blood_NK", "blood_Gran", "blood_Mono"),
  convert_to_M = T,
  return_to_beta = F
)
``` 

```{r eval = F}
save(
  brain_resid,
  blood_resid,
  file = file.path(dir.data.corr, "LONDON_blood_brain_QNBMIQ_PCfiltered_mvalResiduals.rda")
)
```

```{r}
blood_brain_cor <- lapply(seq_len(nrow(brain_resid)), function(row){
  spearman_cor <- cor.test(
    brain_resid[row,],
    blood_resid[row,],
    method = "spearman", 
    exact = F
  )
  
  data.frame(
    cpg = row.names(brain_resid)[row],
    spearman_cor = spearman_cor$estimate,
    pVal = spearman_cor$p.value,
    stringsAsFactors = FALSE
  )
})

blood_brain_cor <- do.call(rbind, blood_brain_cor)
blood_brain_cor$fdr <- p.adjust(blood_brain_cor$pVal, method = "fdr")
blood_brain_cor
```

```{r eval = T}
write.csv(
  blood_brain_cor,
  file.path(dir.data.corr, "London_blood_brain_residuals_correlation_cpgs.csv"),
  row.names = FALSE
)
```

## Beta

```{r}
blood_brain_cor <-  plyr::adply(seq_len(nrow(brain_beta_cpgs)),
                                .margins = 1,
                                .fun =  function(row){
                                  spearman_cor <- cor.test(
                                    brain_beta_cpgs[row,],
                                    blood_beta_cpgs[row,],
                                    method = "spearman",
                                    exact = F
                                  )
                                  
                                  data.frame(
                                    cpg = row.names(brain_beta_cpgs)[row],
                                    spearman_cor = spearman_cor$estimate,
                                    pVal = spearman_cor$p.value,
                                    stringsAsFactors = FALSE
                                  )
                                },.id = NULL)

blood_brain_cor$fdr <- p.adjust(blood_brain_cor$pVal, method = "fdr")
blood_brain_cor
```

```{r eval = T}
write.csv(
  blood_brain_cor,
  file.path(dir.data.corr, "London_blood_brain_beta_correlation_cpgs.csv"),
  row.names = FALSE
)
```

## BECon

```{r message = F}
corr_becon <- readr::read_csv(
  file.path(dir.data.corr,
            "BEcon_results_sig_cpgs.csv")
) %>% dplyr::select(
  c("CpG ID", "Cor Blood-BA7", "Cor Blood- BA10", "Cor Blood- BA20", "Mean Cor All Brain")
)
colnames(corr_becon) <- c(
  "cpg", "BECon_cor_BA7", "BECon_cor_BA10", "BECon_cor_BA20", "BECon_cor_mean"
)
```

# Merge results

```{r message = F}
corr_beta <- read_csv(
  file.path(dir.data.corr, "London_blood_brain_beta_correlation_cpgs.csv")
) %>%
  rename_with(~paste0("beta_", .x), !"cpg")
corr_res <- read_csv(
  file.path(dir.data.corr, "London_blood_brain_residuals_correlation_cpgs.csv")
) %>%
  rename_with(~paste0("res_", .x), !"cpg")
```

## Merge correlation results

```{r message = F, warning=F}
final_results <- full_join(
  full_join(
    corr_beta, corr_res
  ), corr_becon
)
final_results <- unique(final_results)
```

## Merge results

```{r}
final_results_annotate <- left_join(
  final_results,
  results
)
final_results_annotate$cpg_source <- 
  ifelse(!final_results_annotate$cpg %in% sig.dmr, "CpG in single CpG-test",
         ifelse(!final_results_annotate$cpg %in% cpgs.sig, "CpG in DMR", "CpG in both single CpG-test and DMR"))
```

```{r eval = T}
write_csv(
  final_results_annotate,
  file.path(dir.results.corr, 
            "Brain_blood_correlation_results.csv")
)
```
